# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array1= np.array([3,9,8,6,1])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array1_sorted = np.sort(array1)
print(array1_sorted)

[1 3 6 8 9]


# Problem 2

In [2]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
arr2 = np.array([10,15,39,45,60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
arr = np.arange(5, 16)
print(arr)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
arr = np.arange(50, 101, 5)
print(arr)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
arr = np.zeros(10)
print(arr)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
arr = np.ones(10)
print(arr)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
arr = np.linspace(0, 100, 5)
print(arr)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
random_int = np.random.randint(10, 31, size=5)
print(random_int)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
random_floats = np.random.uniform(-1, 1, size=10)
print(random_floats)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_matrix = np.random.randint(10, 51, size=(3, 5))
print(random_matrix)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
row_sums = np.sum(random_matrix, axis=1)
column_sums = np.sum(random_matrix, axis=0)

print("Satir toplamlari:", row_sums)
print("Sütun toplamlari:", column_sums)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max_value = np.max(random_matrix)
min_value = np.min(random_matrix)
mean_value = np.mean(random_matrix)

print("En buyuk deger:", max_value)
print("En kucuk deger:", min_value)
print("Ortalama deger:", mean_value)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.argmax(random_matrix)
print("En buyuk degerin indeksi:", max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
arr = np.arange(10, 21)
ilk_uc = arr[:3]
print(ilk_uc)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
reversed_arr = arr[::-1]
print(reversed_arr)

# 15- Üretilen matrisin ilk satırını seçiniz.
matris = np.random.randint(10, 50, size=(3, 5))
print("Matris:\n", matris)

ilk_satir = matris[0]
print("Ilk satir:\n", ilk_satir)


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
matris = np.random.randint(10, 50, size=(3, 5))
print("Matris:\n", matris)

eleman = matris[1, 2]
print("2. satir 3. sütundaki eleman:", eleman)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
matris = np.random.randint(10, 50, size=(3, 5))
print("Matris:\n", matris)

ilk_elemanlar = matris[:, 0]
print("Tüm satirlardaki ilk elemanlar:\n", ilk_elemanlar)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
matris = np.random.randint(10, 50, size=(3, 5))
print("Matris:\n", matris)

kareleri = np.square(matris)
print("Matrisin elemanlarinin kareleri:\n", kareleri)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris = np.random.randint(-50, 50, size=(3, 5))
pozitif_cift_sayilar = []

for i in range(matris.shape[0]):
    for j in range(matris.shape[1]):
        if matris[i][j] > 0 and matris[i][j] % 2 == 0:
            pozitif_cift_sayilar.append(matris[i][j])

print("Matrisin pozitif çift sayilari:", pozitif_cift_sayilar)


[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[28 18 15 22 12]
[-0.72619675 -0.20337088 -0.01289597  0.14692371  0.63972375  0.2607335
  0.09793738 -0.6029444   0.63979573  0.19749912]
[[11 32 16 18 23]
 [37 40 21 14 44]
 [13 35 27 30 41]]
Satir toplamlari: [100 156 146]
Sütun toplamlari: [ 61 107  64  62 108]
En buyuk deger: 44
En kucuk deger: 11
Ortalama deger: 26.8
En buyuk degerin indeksi: 9
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
Matris:
 [[20 14 43 11 26]
 [14 24 31 40 22]
 [45 35 20 11 17]]
Ilk satir:
 [20 14 43 11 26]
Matris:
 [[35 33 16 44 37]
 [20 42 44 20 27]
 [38 15 28 46 25]]
2. satir 3. sütundaki eleman: 44
Matris:
 [[18 14 39 38 47]
 [25 12 10 21 22]
 [32 16 23 20 29]]
Tüm satirlardaki ilk elemanlar:
 [18 25 32]
Matris:
 [[36 35 44 45 13]
 [31 21 34 18 13]
 [18 13 20 48 38]]
Matrisin elemanlarinin kareleri:
 [[1296 1225 1936 2025  169]
 [ 96